name: clockbox_projet
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.9
  intl_phone_field: ^3.1.0
  gap: ^3.0.1
  pinput: ^3.0.1
  tuple: ^2.0.2
  intl: ^0.18.1
  qr_code_scanner: ^1.0.1
  local_auth: ^2.1.7
  flutter_libphonenumber: ^2.1.5
  flutter_riverpod: ^2.4.9
  mask_text_input_formatter: ^2.7.0
 
  dio: ^5.4.0
  provider: ^6.1.1
  firebase_auth: ^4.15.0
  fluttertoast: ^8.2.4
  flutter_date_range_picker: ^0.0.14
  dropdown_button2: ^2.3.9
  lottie: ^2.7.0
  speech_to_text: ^6.5.1
  supabase_flutter: ^2.1.0
  zkfinger10: ^0.0.5
  internet_connection_checker: ^1.0.0+1
  network_info_plus: ^4.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/countries/